# Generated by Django 5.1 on 2025-08-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient_analysis_app', '0002_alter_ingredientanalysis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientanalysis',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
